name: Terrafy with tfenv
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: rhythmictech/actions-setup-tfenv@v0.0.2
    - run: |
        tfenv -v
        tfenv use 1.1.1
        echo 1.1.0 > .terraform-version
        terraform version
    
